<?php

include_once __DIR__.'/vendor/autoload.php';

define('STOREKEEPER_WOOCOMMERCE_B2C_PHP_VERSION', 7.2);
define('STOREKEEPER_WOOCOMMERCE_B2C_NAME', 'storekeeper-woocommerce-b2c');
define('STOREKEEPER_WOOCOMMERCE_B2C_ABSPATH', __DIR__);
define(
    'STOREKEEPER_WOOCOMMERCE_B2C_ENTRY',
    STOREKEEPER_WOOCOMMERCE_B2C_ABSPATH.'/'.STOREKEEPER_WOOCOMMERCE_B2C_NAME.'.php'
);
