version: '3.7'

services:
  web-test:
    build:
      dockerfile: Dockerfile
      target: test
      context: .
      args:
        - PHP_VERSION
        - WORDPRESS_VERSION
        - WOOCOMMERCE_VERSION
        - WORDPRESS_DOCKER_PHP_VERSION
        - XDEBUG_VERSION
    environment:
      WORDPRESS_DB_HOST: db-test
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: examplepass
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - .:/app/src/wp-content/plugins/storekeeper-for-woocommerce:ro
    networks:
      - test
    depends_on:
      - db-test

  db-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: somerootpassword
    volumes:
      - db-test:/var/lib/mysql
    networks:
      - test

  phpmyadmin-test:
    image: phpmyadmin/phpmyadmin
    links:
      - db-test:db
    ports:
      - 8882:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: somerootpassword
    networks:
      - test
    depends_on:
      - db-test

volumes:
  db-test:


networks:
  test:
    name: test
